// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkyz56aOB7PFF0aNC-HgwInjrezfsinOE',
    appId: '1:439428371661:android:b36d1b51567d6359df8584',
    messagingSenderId: '439428371661',
    projectId: 'image-c0e6f',
    databaseURL: 'https://image-c0e6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'image-c0e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgTwW09IjBSw6f-RED5ewQ1fBxi8L5g0g',
    appId: '1:439428371661:ios:4596142d2fe97c9edf8584',
    messagingSenderId: '439428371661',
    projectId: 'image-c0e6f',
    databaseURL: 'https://image-c0e6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'image-c0e6f.appspot.com',
    iosClientId: '439428371661-jf0dqpoe6n6j62928umflhs10toth4ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
